// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pace_neighbour_kernels_cpp
Rcpp::List pace_neighbour_kernels_cpp(const Rcpp::NumericMatrix& coords, const Rcpp::IntegerVector& neighbour_type, int n_types, const Rcpp::IntegerVector& group, bool per_group, double h_bio, double h_tech, double eps, int n_threads);
RcppExport SEXP _PACE_pace_neighbour_kernels_cpp(SEXP coordsSEXP, SEXP neighbour_typeSEXP, SEXP n_typesSEXP, SEXP groupSEXP, SEXP per_groupSEXP, SEXP h_bioSEXP, SEXP h_techSEXP, SEXP epsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type neighbour_type(neighbour_typeSEXP);
    Rcpp::traits::input_parameter< int >::type n_types(n_typesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< bool >::type per_group(per_groupSEXP);
    Rcpp::traits::input_parameter< double >::type h_bio(h_bioSEXP);
    Rcpp::traits::input_parameter< double >::type h_tech(h_techSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_neighbour_kernels_cpp(coords, neighbour_type, n_types, group, per_group, h_bio, h_tech, eps, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// pace_neighbour_counts_cpp
Rcpp::IntegerVector pace_neighbour_counts_cpp(const Rcpp::NumericMatrix& coords, const Rcpp::IntegerVector& group, bool per_group, double eps, int n_threads);
RcppExport SEXP _PACE_pace_neighbour_counts_cpp(SEXP coordsSEXP, SEXP groupSEXP, SEXP per_groupSEXP, SEXP epsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< bool >::type per_group(per_groupSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_neighbour_counts_cpp(coords, group, per_group, eps, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// pace_neighbour_lists_cpp
Rcpp::List pace_neighbour_lists_cpp(const Rcpp::NumericMatrix& coords, const Rcpp::IntegerVector& group, bool per_group, double eps, int n_threads);
RcppExport SEXP _PACE_pace_neighbour_lists_cpp(SEXP coordsSEXP, SEXP groupSEXP, SEXP per_groupSEXP, SEXP epsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< bool >::type per_group(per_groupSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_neighbour_lists_cpp(coords, group, per_group, eps, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// pace_area_fraction_cpp
Rcpp::NumericVector pace_area_fraction_cpp(const Rcpp::NumericMatrix& coords, double r, double x_min, double x_max, double y_min, double y_max, const Rcpp::NumericVector& cos_theta, const Rcpp::NumericVector& sin_theta, int n_threads);
RcppExport SEXP _PACE_pace_area_fraction_cpp(SEXP coordsSEXP, SEXP rSEXP, SEXP x_minSEXP, SEXP x_maxSEXP, SEXP y_minSEXP, SEXP y_maxSEXP, SEXP cos_thetaSEXP, SEXP sin_thetaSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type x_min(x_minSEXP);
    Rcpp::traits::input_parameter< double >::type x_max(x_maxSEXP);
    Rcpp::traits::input_parameter< double >::type y_min(y_minSEXP);
    Rcpp::traits::input_parameter< double >::type y_max(y_maxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type cos_theta(cos_thetaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type sin_theta(sin_thetaSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_area_fraction_cpp(coords, r, x_min, x_max, y_min, y_max, cos_theta, sin_theta, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// pace_ambient_field_cpp
Rcpp::List pace_ambient_field_cpp(const Rcpp::NumericMatrix& coords, const Rcpp::IntegerVector& type_code, const Rcpp::IntegerVector& image, int n_images, double h_tech, bool edge_correct, const Rcpp::NumericVector& cos_theta, const Rcpp::NumericVector& sin_theta, int n_threads);
RcppExport SEXP _PACE_pace_ambient_field_cpp(SEXP coordsSEXP, SEXP type_codeSEXP, SEXP imageSEXP, SEXP n_imagesSEXP, SEXP h_techSEXP, SEXP edge_correctSEXP, SEXP cos_thetaSEXP, SEXP sin_thetaSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type type_code(type_codeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type image(imageSEXP);
    Rcpp::traits::input_parameter< int >::type n_images(n_imagesSEXP);
    Rcpp::traits::input_parameter< double >::type h_tech(h_techSEXP);
    Rcpp::traits::input_parameter< bool >::type edge_correct(edge_correctSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type cos_theta(cos_thetaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type sin_theta(sin_thetaSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_ambient_field_cpp(coords, type_code, image, n_images, h_tech, edge_correct, cos_theta, sin_theta, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// pace_same_type_fraction_cpp
Rcpp::NumericVector pace_same_type_fraction_cpp(const Rcpp::NumericMatrix& coords, const Rcpp::IntegerVector& type_code, const Rcpp::IntegerVector& image, double radius, int min_image_cells, int n_threads);
RcppExport SEXP _PACE_pace_same_type_fraction_cpp(SEXP coordsSEXP, SEXP type_codeSEXP, SEXP imageSEXP, SEXP radiusSEXP, SEXP min_image_cellsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type coords(coordsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type type_code(type_codeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type image(imageSEXP);
    Rcpp::traits::input_parameter< double >::type radius(radiusSEXP);
    Rcpp::traits::input_parameter< int >::type min_image_cells(min_image_cellsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_same_type_fraction_cpp(coords, type_code, image, radius, min_image_cells, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// pace_group_column_means_cpp
Rcpp::NumericMatrix pace_group_column_means_cpp(const Rcpp::S4& counts, const Rcpp::IntegerVector& group, int n_groups, bool detection, int n_threads);
RcppExport SEXP _PACE_pace_group_column_means_cpp(SEXP countsSEXP, SEXP groupSEXP, SEXP n_groupsSEXP, SEXP detectionSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::S4& >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type n_groups(n_groupsSEXP);
    Rcpp::traits::input_parameter< bool >::type detection(detectionSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_group_column_means_cpp(counts, group, n_groups, detection, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// pace_group_covariances_cpp
Rcpp::NumericVector pace_group_covariances_cpp(const Rcpp::NumericMatrix& values, const Rcpp::IntegerVector& group, int n_groups, int n_threads);
RcppExport SEXP _PACE_pace_group_covariances_cpp(SEXP valuesSEXP, SEXP groupSEXP, SEXP n_groupsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type n_groups(n_groupsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_group_covariances_cpp(values, group, n_groups, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// pace_single_frame_statistics_cpp
Rcpp::List pace_single_frame_statistics_cpp(const Rcpp::S4& counts, const Rcpp::NumericVector& n_count, const Rcpp::IntegerVector& group, int n_groups, int n_threads);
RcppExport SEXP _PACE_pace_single_frame_statistics_cpp(SEXP countsSEXP, SEXP n_countSEXP, SEXP groupSEXP, SEXP n_groupsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::S4& >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type n_count(n_countSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type n_groups(n_groupsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_single_frame_statistics_cpp(counts, n_count, group, n_groups, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// pace_dense_group_moments_cpp
Rcpp::List pace_dense_group_moments_cpp(const Rcpp::NumericMatrix& values, int n, int p, const Rcpp::IntegerVector& group, int n_groups, bool want_mean, bool want_variance, int n_threads);
RcppExport SEXP _PACE_pace_dense_group_moments_cpp(SEXP valuesSEXP, SEXP nSEXP, SEXP pSEXP, SEXP groupSEXP, SEXP n_groupsSEXP, SEXP want_meanSEXP, SEXP want_varianceSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type p(pSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type n_groups(n_groupsSEXP);
    Rcpp::traits::input_parameter< bool >::type want_mean(want_meanSEXP);
    Rcpp::traits::input_parameter< bool >::type want_variance(want_varianceSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_dense_group_moments_cpp(values, n, p, group, n_groups, want_mean, want_variance, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// pace_final_pass_statistics_cpp
Rcpp::List pace_final_pass_statistics_cpp(const Rcpp::NumericMatrix& eta, const Rcpp::NumericVector& offset, const Rcpp::S4& ambient, int first_gene, const Rcpp::NumericVector& rho, const Rcpp::IntegerVector& group, int n_groups, bool want_groups, bool return_matrices);
RcppExport SEXP _PACE_pace_final_pass_statistics_cpp(SEXP etaSEXP, SEXP offsetSEXP, SEXP ambientSEXP, SEXP first_geneSEXP, SEXP rhoSEXP, SEXP groupSEXP, SEXP n_groupsSEXP, SEXP want_groupsSEXP, SEXP return_matricesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::S4& >::type ambient(ambientSEXP);
    Rcpp::traits::input_parameter< int >::type first_gene(first_geneSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type n_groups(n_groupsSEXP);
    Rcpp::traits::input_parameter< bool >::type want_groups(want_groupsSEXP);
    Rcpp::traits::input_parameter< bool >::type return_matrices(return_matricesSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_final_pass_statistics_cpp(eta, offset, ambient, first_gene, rho, group, n_groups, want_groups, return_matrices));
    return rcpp_result_gen;
END_RCPP
}
// pace_variance_decomposition_cpp
Rcpp::List pace_variance_decomposition_cpp(const Rcpp::NumericMatrix& ct_means, const Rcpp::IntegerVector& group_size, const Rcpp::IntegerVector& focal_group, const Rcpp::IntegerVector& n_focal, const Rcpp::NumericMatrix& u, const Rcpp::NumericMatrix& se_u, const Rcpp::IntegerMatrix& slope_rows, const Rcpp::NumericVector& kernel_cov, const Rcpp::IntegerMatrix& responder_rows, const Rcpp::IntegerVector& responder_keep, const Rcpp::NumericVector& responder_cov, const Rcpp::IntegerVector& intercept_rows, const Rcpp::NumericMatrix& toff_var, const Rcpp::NumericVector& spill_cov, const Rcpp::NumericMatrix& beta_spill, const Rcpp::NumericMatrix& mu_mean, const Rcpp::NumericVector& alpha, bool nb1, int n_threads);
RcppExport SEXP _PACE_pace_variance_decomposition_cpp(SEXP ct_meansSEXP, SEXP group_sizeSEXP, SEXP focal_groupSEXP, SEXP n_focalSEXP, SEXP uSEXP, SEXP se_uSEXP, SEXP slope_rowsSEXP, SEXP kernel_covSEXP, SEXP responder_rowsSEXP, SEXP responder_keepSEXP, SEXP responder_covSEXP, SEXP intercept_rowsSEXP, SEXP toff_varSEXP, SEXP spill_covSEXP, SEXP beta_spillSEXP, SEXP mu_meanSEXP, SEXP alphaSEXP, SEXP nb1SEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type ct_means(ct_meansSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type group_size(group_sizeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type focal_group(focal_groupSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type n_focal(n_focalSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type se_u(se_uSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type slope_rows(slope_rowsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type kernel_cov(kernel_covSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type responder_rows(responder_rowsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type responder_keep(responder_keepSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type responder_cov(responder_covSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type intercept_rows(intercept_rowsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type toff_var(toff_varSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type spill_cov(spill_covSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type beta_spill(beta_spillSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mu_mean(mu_meanSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< bool >::type nb1(nb1SEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_variance_decomposition_cpp(ct_means, group_size, focal_group, n_focal, u, se_u, slope_rows, kernel_cov, responder_rows, responder_keep, responder_cov, intercept_rows, toff_var, spill_cov, beta_spill, mu_mean, alpha, nb1, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// pace_decomposition_aggregates_cpp
Rcpp::List pace_decomposition_aggregates_cpp(const Rcpp::IntegerVector& focal_code, int n_focals, const Rcpp::NumericMatrix& pct, const Rcpp::NumericMatrix& components, const Rcpp::NumericVector& spec, const Rcpp::IntegerVector& is_contaminated, bool weight_by_spec_sq);
RcppExport SEXP _PACE_pace_decomposition_aggregates_cpp(SEXP focal_codeSEXP, SEXP n_focalsSEXP, SEXP pctSEXP, SEXP componentsSEXP, SEXP specSEXP, SEXP is_contaminatedSEXP, SEXP weight_by_spec_sqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type focal_code(focal_codeSEXP);
    Rcpp::traits::input_parameter< int >::type n_focals(n_focalsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type pct(pctSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type components(componentsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type spec(specSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type is_contaminated(is_contaminatedSEXP);
    Rcpp::traits::input_parameter< bool >::type weight_by_spec_sq(weight_by_spec_sqSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_decomposition_aggregates_cpp(focal_code, n_focals, pct, components, spec, is_contaminated, weight_by_spec_sq));
    return rcpp_result_gen;
END_RCPP
}
// pace_four_block_shares_cpp
Rcpp::List pace_four_block_shares_cpp(const Rcpp::NumericVector& celltype_offset_sq, const Rcpp::NumericVector& v_state_baseline, const Rcpp::NumericVector& v_state_responder, const Rcpp::NumericVector& v_spill, const Rcpp::NumericVector& v_disp);
RcppExport SEXP _PACE_pace_four_block_shares_cpp(SEXP celltype_offset_sqSEXP, SEXP v_state_baselineSEXP, SEXP v_state_responderSEXP, SEXP v_spillSEXP, SEXP v_dispSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type celltype_offset_sq(celltype_offset_sqSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type v_state_baseline(v_state_baselineSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type v_state_responder(v_state_responderSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type v_spill(v_spillSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type v_disp(v_dispSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_four_block_shares_cpp(celltype_offset_sq, v_state_baseline, v_state_responder, v_spill, v_disp));
    return rcpp_result_gen;
END_RCPP
}
// pace_single_frame_shares_cpp
Rcpp::List pace_single_frame_shares_cpp(const Rcpp::NumericMatrix& focal_mean, const Rcpp::NumericMatrix& within_ss, const Rcpp::NumericVector& global_mean, const Rcpp::IntegerVector& group_size, const Rcpp::NumericMatrix& v_state, const Rcpp::NumericMatrix& v_responder, const Rcpp::NumericMatrix& v_spill, const Rcpp::NumericMatrix& v_disp, int n_threads);
RcppExport SEXP _PACE_pace_single_frame_shares_cpp(SEXP focal_meanSEXP, SEXP within_ssSEXP, SEXP global_meanSEXP, SEXP group_sizeSEXP, SEXP v_stateSEXP, SEXP v_responderSEXP, SEXP v_spillSEXP, SEXP v_dispSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type focal_mean(focal_meanSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type within_ss(within_ssSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type global_mean(global_meanSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type group_size(group_sizeSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type v_state(v_stateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type v_responder(v_responderSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type v_spill(v_spillSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type v_disp(v_dispSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_single_frame_shares_cpp(focal_mean, within_ss, global_mean, group_size, v_state, v_responder, v_spill, v_disp, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// pace_driver_scores_cpp
Rcpp::List pace_driver_scores_cpp(const Rcpp::NumericVector& estimate_shrunk, const Rcpp::NumericVector& spec, const Rcpp::NumericVector& focal_mean, const Rcpp::NumericVector& mu_bar, const Rcpp::NumericVector& alpha, const Rcpp::NumericVector& u_raw, double var_n, double var_rn, bool has_responder);
RcppExport SEXP _PACE_pace_driver_scores_cpp(SEXP estimate_shrunkSEXP, SEXP specSEXP, SEXP focal_meanSEXP, SEXP mu_barSEXP, SEXP alphaSEXP, SEXP u_rawSEXP, SEXP var_nSEXP, SEXP var_rnSEXP, SEXP has_responderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type estimate_shrunk(estimate_shrunkSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type spec(specSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type focal_mean(focal_meanSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type mu_bar(mu_barSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type u_raw(u_rawSEXP);
    Rcpp::traits::input_parameter< double >::type var_n(var_nSEXP);
    Rcpp::traits::input_parameter< double >::type var_rn(var_rnSEXP);
    Rcpp::traits::input_parameter< bool >::type has_responder(has_responderSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_driver_scores_cpp(estimate_shrunk, spec, focal_mean, mu_bar, alpha, u_raw, var_n, var_rn, has_responder));
    return rcpp_result_gen;
END_RCPP
}
// pace_subset_covariance_cpp
Rcpp::NumericMatrix pace_subset_covariance_cpp(const Rcpp::S4& matrix, const Rcpp::IntegerVector& rows, const Rcpp::IntegerVector& cols, const Rcpp::NumericVector& scale);
RcppExport SEXP _PACE_pace_subset_covariance_cpp(SEXP matrixSEXP, SEXP rowsSEXP, SEXP colsSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::S4& >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type cols(colsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_subset_covariance_cpp(matrix, rows, cols, scale));
    return rcpp_result_gen;
END_RCPP
}
// pace_subset_column_cpp
Rcpp::NumericVector pace_subset_column_cpp(const Rcpp::S4& matrix, const Rcpp::IntegerVector& rows, int column);
RcppExport SEXP _PACE_pace_subset_column_cpp(SEXP matrixSEXP, SEXP rowsSEXP, SEXP columnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::S4& >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< int >::type column(columnSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_subset_column_cpp(matrix, rows, column));
    return rcpp_result_gen;
END_RCPP
}
// pace_column_nonzero_rows_cpp
Rcpp::IntegerVector pace_column_nonzero_rows_cpp(const Rcpp::S4& matrix, int column);
RcppExport SEXP _PACE_pace_column_nonzero_rows_cpp(SEXP matrixSEXP, SEXP columnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::S4& >::type matrix(matrixSEXP);
    Rcpp::traits::input_parameter< int >::type column(columnSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_column_nonzero_rows_cpp(matrix, column));
    return rcpp_result_gen;
END_RCPP
}
// pace_pair_variance_pratt_cpp
Rcpp::List pace_pair_variance_pratt_cpp(const Rcpp::NumericMatrix& sigma, const Rcpp::NumericMatrix& u);
RcppExport SEXP _PACE_pace_pair_variance_pratt_cpp(SEXP sigmaSEXP, SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type u(uSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_pair_variance_pratt_cpp(sigma, u));
    return rcpp_result_gen;
END_RCPP
}
// pace_single_frame_focal_blocks_cpp
Rcpp::NumericMatrix pace_single_frame_focal_blocks_cpp(const Rcpp::IntegerVector& focal_code, int n_focals, const Rcpp::NumericMatrix& pct, const Rcpp::NumericVector& denom);
RcppExport SEXP _PACE_pace_single_frame_focal_blocks_cpp(SEXP focal_codeSEXP, SEXP n_focalsSEXP, SEXP pctSEXP, SEXP denomSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type focal_code(focal_codeSEXP);
    Rcpp::traits::input_parameter< int >::type n_focals(n_focalsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type pct(pctSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type denom(denomSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_single_frame_focal_blocks_cpp(focal_code, n_focals, pct, denom));
    return rcpp_result_gen;
END_RCPP
}
// pace_all_finite_cpp
bool pace_all_finite_cpp(const Rcpp::NumericVector& values);
RcppExport SEXP _PACE_pace_all_finite_cpp(SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type values(valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_all_finite_cpp(values));
    return rcpp_result_gen;
END_RCPP
}
// pace_working_response_cpp
Rcpp::List pace_working_response_cpp(const Rcpp::NumericMatrix& eta, const Rcpp::S4& counts, const Rcpp::S4& ambient, int first_gene, int n_genes, const Rcpp::NumericVector& offset, const Rcpp::NumericVector& rho, const Rcpp::NumericVector& alpha, const Rcpp::NumericVector& sample_weight, bool nb2, bool seed_iteration, int n_cells, int n_threads);
RcppExport SEXP _PACE_pace_working_response_cpp(SEXP etaSEXP, SEXP countsSEXP, SEXP ambientSEXP, SEXP first_geneSEXP, SEXP n_genesSEXP, SEXP offsetSEXP, SEXP rhoSEXP, SEXP alphaSEXP, SEXP sample_weightSEXP, SEXP nb2SEXP, SEXP seed_iterationSEXP, SEXP n_cellsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::S4& >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::S4& >::type ambient(ambientSEXP);
    Rcpp::traits::input_parameter< int >::type first_gene(first_geneSEXP);
    Rcpp::traits::input_parameter< int >::type n_genes(n_genesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type sample_weight(sample_weightSEXP);
    Rcpp::traits::input_parameter< bool >::type nb2(nb2SEXP);
    Rcpp::traits::input_parameter< bool >::type seed_iteration(seed_iterationSEXP);
    Rcpp::traits::input_parameter< int >::type n_cells(n_cellsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_working_response_cpp(eta, counts, ambient, first_gene, n_genes, offset, rho, alpha, sample_weight, nb2, seed_iteration, n_cells, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// pace_rho_accumulate_cpp
Rcpp::List pace_rho_accumulate_cpp(const Rcpp::NumericMatrix& eta, const Rcpp::NumericMatrix& prev_eta, const Rcpp::S4& counts, const Rcpp::S4& ambient, int first_gene, const Rcpp::NumericVector& offset, const Rcpp::NumericVector& rho, const Rcpp::NumericVector& alpha, const Rcpp::NumericMatrix& mask, const Rcpp::IntegerVector& mask_index, const Rcpp::NumericVector& num_in, const Rcpp::NumericVector& den_in, bool nb2, bool seed_iteration, bool seed_previous, int n_cells, int n_genes_in, bool want_tail_counts);
RcppExport SEXP _PACE_pace_rho_accumulate_cpp(SEXP etaSEXP, SEXP prev_etaSEXP, SEXP countsSEXP, SEXP ambientSEXP, SEXP first_geneSEXP, SEXP offsetSEXP, SEXP rhoSEXP, SEXP alphaSEXP, SEXP maskSEXP, SEXP mask_indexSEXP, SEXP num_inSEXP, SEXP den_inSEXP, SEXP nb2SEXP, SEXP seed_iterationSEXP, SEXP seed_previousSEXP, SEXP n_cellsSEXP, SEXP n_genes_inSEXP, SEXP want_tail_countsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type prev_eta(prev_etaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::S4& >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::S4& >::type ambient(ambientSEXP);
    Rcpp::traits::input_parameter< int >::type first_gene(first_geneSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type mask(maskSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type mask_index(mask_indexSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type num_in(num_inSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type den_in(den_inSEXP);
    Rcpp::traits::input_parameter< bool >::type nb2(nb2SEXP);
    Rcpp::traits::input_parameter< bool >::type seed_iteration(seed_iterationSEXP);
    Rcpp::traits::input_parameter< bool >::type seed_previous(seed_previousSEXP);
    Rcpp::traits::input_parameter< int >::type n_cells(n_cellsSEXP);
    Rcpp::traits::input_parameter< int >::type n_genes_in(n_genes_inSEXP);
    Rcpp::traits::input_parameter< bool >::type want_tail_counts(want_tail_countsSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_rho_accumulate_cpp(eta, prev_eta, counts, ambient, first_gene, offset, rho, alpha, mask, mask_index, num_in, den_in, nb2, seed_iteration, seed_previous, n_cells, n_genes_in, want_tail_counts));
    return rcpp_result_gen;
END_RCPP
}
// pace_fitted_mean_column_cpp
Rcpp::List pace_fitted_mean_column_cpp(const Rcpp::NumericVector& eta_column, const Rcpp::S4& counts, const Rcpp::S4& ambient, int first_gene, int gene, const Rcpp::NumericVector& offset, const Rcpp::NumericVector& rho);
RcppExport SEXP _PACE_pace_fitted_mean_column_cpp(SEXP eta_columnSEXP, SEXP countsSEXP, SEXP ambientSEXP, SEXP first_geneSEXP, SEXP geneSEXP, SEXP offsetSEXP, SEXP rhoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type eta_column(eta_columnSEXP);
    Rcpp::traits::input_parameter< const Rcpp::S4& >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::S4& >::type ambient(ambientSEXP);
    Rcpp::traits::input_parameter< int >::type first_gene(first_geneSEXP);
    Rcpp::traits::input_parameter< int >::type gene(geneSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type rho(rhoSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_fitted_mean_column_cpp(eta_column, counts, ambient, first_gene, gene, offset, rho));
    return rcpp_result_gen;
END_RCPP
}
// pace_rho_shrink_cpp
Rcpp::List pace_rho_shrink_cpp(const Rcpp::NumericVector& num, const Rcpp::NumericVector& den);
RcppExport SEXP _PACE_pace_rho_shrink_cpp(SEXP numSEXP, SEXP denSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type num(numSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type den(denSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_rho_shrink_cpp(num, den));
    return rcpp_result_gen;
END_RCPP
}
// pace_tau_em_update_cpp
Rcpp::NumericVector pace_tau_em_update_cpp(const Rcpp::NumericMatrix& u, const Rcpp::NumericMatrix& re_var);
RcppExport SEXP _PACE_pace_tau_em_update_cpp(SEXP uSEXP, SEXP re_varSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type u(uSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type re_var(re_varSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_tau_em_update_cpp(u, re_var));
    return rcpp_result_gen;
END_RCPP
}
// pace_tau_hierarchical_cpp
Rcpp::NumericMatrix pace_tau_hierarchical_cpp(const Rcpp::NumericMatrix& tau, const Rcpp::IntegerVector& n_group, double lambda_factor);
RcppExport SEXP _PACE_pace_tau_hierarchical_cpp(SEXP tauSEXP, SEXP n_groupSEXP, SEXP lambda_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type n_group(n_groupSEXP);
    Rcpp::traits::input_parameter< double >::type lambda_factor(lambda_factorSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_tau_hierarchical_cpp(tau, n_group, lambda_factor));
    return rcpp_result_gen;
END_RCPP
}
// pace_tau_eb_summaries_cpp
Rcpp::List pace_tau_eb_summaries_cpp(const Rcpp::NumericMatrix& s2, double reml_factor);
RcppExport SEXP _PACE_pace_tau_eb_summaries_cpp(SEXP s2SEXP, SEXP reml_factorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< double >::type reml_factor(reml_factorSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_tau_eb_summaries_cpp(s2, reml_factor));
    return rcpp_result_gen;
END_RCPP
}
// pace_tau_eb_apply_cpp
Rcpp::NumericMatrix pace_tau_eb_apply_cpp(const Rcpp::NumericMatrix& s2, double reml_factor, const Rcpp::NumericVector& panel, const Rcpp::NumericVector& panel_median, const Rcpp::NumericVector& d0, double tau_floor);
RcppExport SEXP _PACE_pace_tau_eb_apply_cpp(SEXP s2SEXP, SEXP reml_factorSEXP, SEXP panelSEXP, SEXP panel_medianSEXP, SEXP d0SEXP, SEXP tau_floorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< double >::type reml_factor(reml_factorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type panel(panelSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type panel_median(panel_medianSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type d0(d0SEXP);
    Rcpp::traits::input_parameter< double >::type tau_floor(tau_floorSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_tau_eb_apply_cpp(s2, reml_factor, panel, panel_median, d0, tau_floor));
    return rcpp_result_gen;
END_RCPP
}
// pace_tau_half_cauchy_cpp
Rcpp::List pace_tau_half_cauchy_cpp(const Rcpp::NumericMatrix& s2, int n_em_iter, double tau_floor, const Rcpp::NumericVector& lambda2_prev, const Rcpp::NumericMatrix& a_prev);
RcppExport SEXP _PACE_pace_tau_half_cauchy_cpp(SEXP s2SEXP, SEXP n_em_iterSEXP, SEXP tau_floorSEXP, SEXP lambda2_prevSEXP, SEXP a_prevSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< int >::type n_em_iter(n_em_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tau_floor(tau_floorSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type lambda2_prev(lambda2_prevSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type a_prev(a_prevSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_tau_half_cauchy_cpp(s2, n_em_iter, tau_floor, lambda2_prev, a_prev));
    return rcpp_result_gen;
END_RCPP
}
// pace_tau_clamp_cpp
Rcpp::List pace_tau_clamp_cpp(const Rcpp::NumericMatrix& tau, double tau_max);
RcppExport SEXP _PACE_pace_tau_clamp_cpp(SEXP tauSEXP, SEXP tau_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type tau_max(tau_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_tau_clamp_cpp(tau, tau_max));
    return rcpp_result_gen;
END_RCPP
}
// pace_data_informed_weights_cpp
Rcpp::NumericMatrix pace_data_informed_weights_cpp(const Rcpp::NumericMatrix& detection_rate, const Rcpp::IntegerVector& focal_of_row, const Rcpp::NumericVector& scale_of_row);
RcppExport SEXP _PACE_pace_data_informed_weights_cpp(SEXP detection_rateSEXP, SEXP focal_of_rowSEXP, SEXP scale_of_rowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type detection_rate(detection_rateSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type focal_of_row(focal_of_rowSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type scale_of_row(scale_of_rowSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_data_informed_weights_cpp(detection_rate, focal_of_row, scale_of_row));
    return rcpp_result_gen;
END_RCPP
}
// pace_solve_genes_chunk_cpp
Rcpp::List pace_solve_genes_chunk_cpp(const Rcpp::NumericMatrix& x_fixed, const Rcpp::NumericMatrix& w, const Rcpp::NumericMatrix& z, const Rcpp::NumericMatrix& lam_diag, int q_total, const Rcpp::List& blocks, const Rcpp::List& terms_list, const Rcpp::List& cells_by_group_list, const Rcpp::List& cell_group_list, bool single_precision, int n_threads);
RcppExport SEXP _PACE_pace_solve_genes_chunk_cpp(SEXP x_fixedSEXP, SEXP wSEXP, SEXP zSEXP, SEXP lam_diagSEXP, SEXP q_totalSEXP, SEXP blocksSEXP, SEXP terms_listSEXP, SEXP cells_by_group_listSEXP, SEXP cell_group_listSEXP, SEXP single_precisionSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type x_fixed(x_fixedSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type lam_diag(lam_diagSEXP);
    Rcpp::traits::input_parameter< int >::type q_total(q_totalSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type blocks(blocksSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type terms_list(terms_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type cells_by_group_list(cells_by_group_listSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type cell_group_list(cell_group_listSEXP);
    Rcpp::traits::input_parameter< bool >::type single_precision(single_precisionSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(pace_solve_genes_chunk_cpp(x_fixed, w, z, lam_diag, q_total, blocks, terms_list, cells_by_group_list, cell_group_list, single_precision, n_threads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PACE_pace_neighbour_kernels_cpp", (DL_FUNC) &_PACE_pace_neighbour_kernels_cpp, 9},
    {"_PACE_pace_neighbour_counts_cpp", (DL_FUNC) &_PACE_pace_neighbour_counts_cpp, 5},
    {"_PACE_pace_neighbour_lists_cpp", (DL_FUNC) &_PACE_pace_neighbour_lists_cpp, 5},
    {"_PACE_pace_area_fraction_cpp", (DL_FUNC) &_PACE_pace_area_fraction_cpp, 9},
    {"_PACE_pace_ambient_field_cpp", (DL_FUNC) &_PACE_pace_ambient_field_cpp, 9},
    {"_PACE_pace_same_type_fraction_cpp", (DL_FUNC) &_PACE_pace_same_type_fraction_cpp, 6},
    {"_PACE_pace_group_column_means_cpp", (DL_FUNC) &_PACE_pace_group_column_means_cpp, 5},
    {"_PACE_pace_group_covariances_cpp", (DL_FUNC) &_PACE_pace_group_covariances_cpp, 4},
    {"_PACE_pace_single_frame_statistics_cpp", (DL_FUNC) &_PACE_pace_single_frame_statistics_cpp, 5},
    {"_PACE_pace_dense_group_moments_cpp", (DL_FUNC) &_PACE_pace_dense_group_moments_cpp, 8},
    {"_PACE_pace_final_pass_statistics_cpp", (DL_FUNC) &_PACE_pace_final_pass_statistics_cpp, 9},
    {"_PACE_pace_variance_decomposition_cpp", (DL_FUNC) &_PACE_pace_variance_decomposition_cpp, 19},
    {"_PACE_pace_decomposition_aggregates_cpp", (DL_FUNC) &_PACE_pace_decomposition_aggregates_cpp, 7},
    {"_PACE_pace_four_block_shares_cpp", (DL_FUNC) &_PACE_pace_four_block_shares_cpp, 5},
    {"_PACE_pace_single_frame_shares_cpp", (DL_FUNC) &_PACE_pace_single_frame_shares_cpp, 9},
    {"_PACE_pace_driver_scores_cpp", (DL_FUNC) &_PACE_pace_driver_scores_cpp, 9},
    {"_PACE_pace_subset_covariance_cpp", (DL_FUNC) &_PACE_pace_subset_covariance_cpp, 4},
    {"_PACE_pace_subset_column_cpp", (DL_FUNC) &_PACE_pace_subset_column_cpp, 3},
    {"_PACE_pace_column_nonzero_rows_cpp", (DL_FUNC) &_PACE_pace_column_nonzero_rows_cpp, 2},
    {"_PACE_pace_pair_variance_pratt_cpp", (DL_FUNC) &_PACE_pace_pair_variance_pratt_cpp, 2},
    {"_PACE_pace_single_frame_focal_blocks_cpp", (DL_FUNC) &_PACE_pace_single_frame_focal_blocks_cpp, 4},
    {"_PACE_pace_all_finite_cpp", (DL_FUNC) &_PACE_pace_all_finite_cpp, 1},
    {"_PACE_pace_working_response_cpp", (DL_FUNC) &_PACE_pace_working_response_cpp, 13},
    {"_PACE_pace_rho_accumulate_cpp", (DL_FUNC) &_PACE_pace_rho_accumulate_cpp, 18},
    {"_PACE_pace_fitted_mean_column_cpp", (DL_FUNC) &_PACE_pace_fitted_mean_column_cpp, 7},
    {"_PACE_pace_rho_shrink_cpp", (DL_FUNC) &_PACE_pace_rho_shrink_cpp, 2},
    {"_PACE_pace_tau_em_update_cpp", (DL_FUNC) &_PACE_pace_tau_em_update_cpp, 2},
    {"_PACE_pace_tau_hierarchical_cpp", (DL_FUNC) &_PACE_pace_tau_hierarchical_cpp, 3},
    {"_PACE_pace_tau_eb_summaries_cpp", (DL_FUNC) &_PACE_pace_tau_eb_summaries_cpp, 2},
    {"_PACE_pace_tau_eb_apply_cpp", (DL_FUNC) &_PACE_pace_tau_eb_apply_cpp, 6},
    {"_PACE_pace_tau_half_cauchy_cpp", (DL_FUNC) &_PACE_pace_tau_half_cauchy_cpp, 5},
    {"_PACE_pace_tau_clamp_cpp", (DL_FUNC) &_PACE_pace_tau_clamp_cpp, 2},
    {"_PACE_pace_data_informed_weights_cpp", (DL_FUNC) &_PACE_pace_data_informed_weights_cpp, 3},
    {"_PACE_pace_solve_genes_chunk_cpp", (DL_FUNC) &_PACE_pace_solve_genes_chunk_cpp, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_PACE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
