# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pace_neighbour_kernels_cpp <- function(coords, neighbour_type, n_types, group, per_group, h_bio, h_tech, eps, n_threads) {
    .Call(`_PACE_pace_neighbour_kernels_cpp`, coords, neighbour_type, n_types, group, per_group, h_bio, h_tech, eps, n_threads)
}

pace_neighbour_counts_cpp <- function(coords, group, per_group, eps, n_threads) {
    .Call(`_PACE_pace_neighbour_counts_cpp`, coords, group, per_group, eps, n_threads)
}

pace_neighbour_lists_cpp <- function(coords, group, per_group, eps, n_threads) {
    .Call(`_PACE_pace_neighbour_lists_cpp`, coords, group, per_group, eps, n_threads)
}

pace_area_fraction_cpp <- function(coords, r, x_min, x_max, y_min, y_max, cos_theta, sin_theta, n_threads) {
    .Call(`_PACE_pace_area_fraction_cpp`, coords, r, x_min, x_max, y_min, y_max, cos_theta, sin_theta, n_threads)
}

pace_ambient_field_cpp <- function(coords, type_code, image, n_images, h_tech, edge_correct, cos_theta, sin_theta, n_threads) {
    .Call(`_PACE_pace_ambient_field_cpp`, coords, type_code, image, n_images, h_tech, edge_correct, cos_theta, sin_theta, n_threads)
}

pace_same_type_fraction_cpp <- function(coords, type_code, image, radius, min_image_cells, n_threads) {
    .Call(`_PACE_pace_same_type_fraction_cpp`, coords, type_code, image, radius, min_image_cells, n_threads)
}

pace_group_column_means_cpp <- function(counts, group, n_groups, detection, n_threads) {
    .Call(`_PACE_pace_group_column_means_cpp`, counts, group, n_groups, detection, n_threads)
}

pace_group_covariances_cpp <- function(values, group, n_groups, n_threads) {
    .Call(`_PACE_pace_group_covariances_cpp`, values, group, n_groups, n_threads)
}

pace_single_frame_statistics_cpp <- function(counts, n_count, group, n_groups, n_threads) {
    .Call(`_PACE_pace_single_frame_statistics_cpp`, counts, n_count, group, n_groups, n_threads)
}

pace_dense_group_moments_cpp <- function(values, n, p, group, n_groups, want_mean, want_variance, n_threads) {
    .Call(`_PACE_pace_dense_group_moments_cpp`, values, n, p, group, n_groups, want_mean, want_variance, n_threads)
}

pace_final_pass_statistics_cpp <- function(eta, offset, ambient, first_gene, rho, group, n_groups, want_groups, return_matrices) {
    .Call(`_PACE_pace_final_pass_statistics_cpp`, eta, offset, ambient, first_gene, rho, group, n_groups, want_groups, return_matrices)
}

pace_variance_decomposition_cpp <- function(ct_means, group_size, focal_group, n_focal, u, se_u, slope_rows, kernel_cov, responder_rows, responder_keep, responder_cov, intercept_rows, toff_var, spill_cov, beta_spill, mu_mean, alpha, nb1, n_threads) {
    .Call(`_PACE_pace_variance_decomposition_cpp`, ct_means, group_size, focal_group, n_focal, u, se_u, slope_rows, kernel_cov, responder_rows, responder_keep, responder_cov, intercept_rows, toff_var, spill_cov, beta_spill, mu_mean, alpha, nb1, n_threads)
}

pace_decomposition_aggregates_cpp <- function(focal_code, n_focals, pct, components, spec, is_contaminated, weight_by_spec_sq) {
    .Call(`_PACE_pace_decomposition_aggregates_cpp`, focal_code, n_focals, pct, components, spec, is_contaminated, weight_by_spec_sq)
}

pace_four_block_shares_cpp <- function(celltype_offset_sq, v_state_baseline, v_state_responder, v_spill, v_disp) {
    .Call(`_PACE_pace_four_block_shares_cpp`, celltype_offset_sq, v_state_baseline, v_state_responder, v_spill, v_disp)
}

pace_single_frame_shares_cpp <- function(focal_mean, within_ss, global_mean, group_size, v_state, v_responder, v_spill, v_disp, n_threads) {
    .Call(`_PACE_pace_single_frame_shares_cpp`, focal_mean, within_ss, global_mean, group_size, v_state, v_responder, v_spill, v_disp, n_threads)
}

pace_driver_scores_cpp <- function(estimate_shrunk, spec, focal_mean, mu_bar, alpha, u_raw, var_n, var_rn, has_responder) {
    .Call(`_PACE_pace_driver_scores_cpp`, estimate_shrunk, spec, focal_mean, mu_bar, alpha, u_raw, var_n, var_rn, has_responder)
}

pace_subset_covariance_cpp <- function(matrix, rows, cols, scale) {
    .Call(`_PACE_pace_subset_covariance_cpp`, matrix, rows, cols, scale)
}

pace_subset_column_cpp <- function(matrix, rows, column) {
    .Call(`_PACE_pace_subset_column_cpp`, matrix, rows, column)
}

pace_column_nonzero_rows_cpp <- function(matrix, column) {
    .Call(`_PACE_pace_column_nonzero_rows_cpp`, matrix, column)
}

pace_pair_variance_pratt_cpp <- function(sigma, u) {
    .Call(`_PACE_pace_pair_variance_pratt_cpp`, sigma, u)
}

pace_single_frame_focal_blocks_cpp <- function(focal_code, n_focals, pct, denom) {
    .Call(`_PACE_pace_single_frame_focal_blocks_cpp`, focal_code, n_focals, pct, denom)
}

pace_all_finite_cpp <- function(values) {
    .Call(`_PACE_pace_all_finite_cpp`, values)
}

pace_working_response_cpp <- function(eta, counts, ambient, first_gene, n_genes, offset, rho, alpha, sample_weight, nb2, gaussian, seed_iteration, n_cells, n_threads) {
    .Call(`_PACE_pace_working_response_cpp`, eta, counts, ambient, first_gene, n_genes, offset, rho, alpha, sample_weight, nb2, gaussian, seed_iteration, n_cells, n_threads)
}

pace_rho_accumulate_cpp <- function(eta, prev_eta, counts, ambient, first_gene, offset, rho, alpha, mask, mask_index, num_in, den_in, nb2, seed_iteration, seed_previous, n_cells, n_genes_in, want_tail_counts, n_threads) {
    .Call(`_PACE_pace_rho_accumulate_cpp`, eta, prev_eta, counts, ambient, first_gene, offset, rho, alpha, mask, mask_index, num_in, den_in, nb2, seed_iteration, seed_previous, n_cells, n_genes_in, want_tail_counts, n_threads)
}

pace_fitted_mean_column_cpp <- function(eta_column, counts, ambient, first_gene, gene, offset, rho) {
    .Call(`_PACE_pace_fitted_mean_column_cpp`, eta_column, counts, ambient, first_gene, gene, offset, rho)
}

pace_rho_shrink_cpp <- function(num, den) {
    .Call(`_PACE_pace_rho_shrink_cpp`, num, den)
}

pace_tau_em_update_cpp <- function(u, re_var) {
    .Call(`_PACE_pace_tau_em_update_cpp`, u, re_var)
}

pace_tau_hierarchical_cpp <- function(tau, n_group, lambda_factor) {
    .Call(`_PACE_pace_tau_hierarchical_cpp`, tau, n_group, lambda_factor)
}

pace_tau_eb_summaries_cpp <- function(s2, reml_factor) {
    .Call(`_PACE_pace_tau_eb_summaries_cpp`, s2, reml_factor)
}

pace_tau_eb_apply_cpp <- function(s2, reml_factor, panel, panel_median, d0, tau_floor) {
    .Call(`_PACE_pace_tau_eb_apply_cpp`, s2, reml_factor, panel, panel_median, d0, tau_floor)
}

pace_tau_half_cauchy_cpp <- function(s2, n_em_iter, tau_floor, lambda2_prev, a_prev) {
    .Call(`_PACE_pace_tau_half_cauchy_cpp`, s2, n_em_iter, tau_floor, lambda2_prev, a_prev)
}

pace_tau_clamp_cpp <- function(tau, tau_max) {
    .Call(`_PACE_pace_tau_clamp_cpp`, tau, tau_max)
}

pace_data_informed_weights_cpp <- function(detection_rate, focal_of_row, scale_of_row) {
    .Call(`_PACE_pace_data_informed_weights_cpp`, detection_rate, focal_of_row, scale_of_row)
}

pace_solve_genes_chunk_cpp <- function(x_fixed, w, z, lam_diag, q_total, blocks, terms_list, cells_by_group_list, cell_group_list, single_precision, n_threads) {
    .Call(`_PACE_pace_solve_genes_chunk_cpp`, x_fixed, w, z, lam_diag, q_total, blocks, terms_list, cells_by_group_list, cell_group_list, single_precision, n_threads)
}

pace_dispersion_chunk_cpp <- function(eta, counts, ambient, first_gene, offset, rho, nb2, zero_collapse, max_cells, fast_density, n_threads) {
    .Call(`_PACE_pace_dispersion_chunk_cpp`, eta, counts, ambient, first_gene, offset, rho, nb2, zero_collapse, max_cells, fast_density, n_threads)
}

pace_dispersion_mle_cpp <- function(counts, mu, nb2, zero_collapse, max_cells, fast_density) {
    .Call(`_PACE_pace_dispersion_mle_cpp`, counts, mu, nb2, zero_collapse, max_cells, fast_density)
}

pace_estimate_d0_cpp <- function(log_variance, n_used, d0_max) {
    .Call(`_PACE_pace_estimate_d0_cpp`, log_variance, n_used, d0_max)
}

pace_drop_sparse_kernel_cpp <- function(kernel, celltype, min_effective) {
    .Call(`_PACE_pace_drop_sparse_kernel_cpp`, kernel, celltype, min_effective)
}

pace_centre_within_groups_cpp <- function(kernel, image, celltype, n_images, n_celltypes) {
    .Call(`_PACE_pace_centre_within_groups_cpp`, kernel, image, celltype, n_images, n_celltypes)
}

pace_standardise_cpp <- function(values) {
    .Call(`_PACE_pace_standardise_cpp`, values)
}

pace_anchor_mask_cpp <- function(core_means, owner_threshold, core_threshold) {
    .Call(`_PACE_pace_anchor_mask_cpp`, core_means, owner_threshold, core_threshold)
}

pace_normalise_rows_to_max_cpp <- function(values) {
    .Call(`_PACE_pace_normalise_rows_to_max_cpp`, values)
}

pace_eta_block_cpp <- function(x1, x1_is_unit, x_fixed, p, b, z_design, u, genes, n_threads) {
    .Call(`_PACE_pace_eta_block_cpp`, x1, x1_is_unit, x_fixed, p, b, z_design, u, genes, n_threads)
}

pace_rho_pass_cpp <- function(x1, x1_is_unit, x_fixed, p, z_design, b_in, u_in, prev_b, prev_u, have_previous, counts, ambient, offset, rho, alpha, mask, mask_index, nb2, want_tail_counts, n_cells, chunk_size, n_threads) {
    .Call(`_PACE_pace_rho_pass_cpp`, x1, x1_is_unit, x_fixed, p, z_design, b_in, u_in, prev_b, prev_u, have_previous, counts, ambient, offset, rho, alpha, mask, mask_index, nb2, want_tail_counts, n_cells, chunk_size, n_threads)
}

pace_marginal_variance_cpp <- function(counts, floor_value, n_cells, n_genes, n_threads) {
    .Call(`_PACE_pace_marginal_variance_cpp`, counts, floor_value, n_cells, n_genes, n_threads)
}

pace_dispersion_pass_cpp <- function(x1, x1_is_unit, x_fixed, p, z_design, b_in, u_in, counts, ambient, offset, rho, nb2, gaussian, zero_collapse, max_cells, fast_density, n_cells, chunk_size, n_threads) {
    .Call(`_PACE_pace_dispersion_pass_cpp`, x1, x1_is_unit, x_fixed, p, z_design, b_in, u_in, counts, ambient, offset, rho, nb2, gaussian, zero_collapse, max_cells, fast_density, n_cells, chunk_size, n_threads)
}

pace_fit_pass1_cpp <- function(x1, x1_is_unit, x_fixed, solve_x_fixed, p, z_design, blocks, terms_list, cells_by_group_list, cell_group_list, b_in, u_in, lam_diag, counts, ambient, offset, rho, alpha, sample_weight, nb2, gaussian, seed_iteration, n_cells, chunk_size, sub_genes, interior_precision, last_iter, n_threads) {
    .Call(`_PACE_pace_fit_pass1_cpp`, x1, x1_is_unit, x_fixed, solve_x_fixed, p, z_design, blocks, terms_list, cells_by_group_list, cell_group_list, b_in, u_in, lam_diag, counts, ambient, offset, rho, alpha, sample_weight, nb2, gaussian, seed_iteration, n_cells, chunk_size, sub_genes, interior_precision, last_iter, n_threads)
}

pace_working_response_chunk_cpp <- function(eta_chunk, x1, x1_is_unit, x_fixed, p, b, z_design, u, genes, counts, ambient, first_gene, offset, rho, alpha, sample_weight, nb2, gaussian, seed_iteration, n_cells, sub_genes, n_threads) {
    .Call(`_PACE_pace_working_response_chunk_cpp`, eta_chunk, x1, x1_is_unit, x_fixed, p, b, z_design, u, genes, counts, ambient, first_gene, offset, rho, alpha, sample_weight, nb2, gaussian, seed_iteration, n_cells, sub_genes, n_threads)
}

pace_irls_driver_cpp <- function(x1, x1_is_unit, x_fixed, solve_x_fixed, p, z_design, blocks, terms_list, cells_by_group_list, cell_group_list, counts, ambient, offset, sample_weight, mask, mask_index, data_informed_weights, alpha_init, gene_names, n_cells, q_total, n_genes, n_iter, min_iter, early_stop_tol, alpha_warmup, alpha_warmup_label, nb2, gaussian, zero_collapse, alpha_max_cells, fast_density, interior_precision, chunk_size, sub_genes, tau_max, tau_shrinkage, d0_min, use_reml, rd_diag, verbose, n_threads) {
    .Call(`_PACE_pace_irls_driver_cpp`, x1, x1_is_unit, x_fixed, solve_x_fixed, p, z_design, blocks, terms_list, cells_by_group_list, cell_group_list, counts, ambient, offset, sample_weight, mask, mask_index, data_informed_weights, alpha_init, gene_names, n_cells, q_total, n_genes, n_iter, min_iter, early_stop_tol, alpha_warmup, alpha_warmup_label, nb2, gaussian, zero_collapse, alpha_max_cells, fast_density, interior_precision, chunk_size, sub_genes, tau_max, tau_shrinkage, d0_min, use_reml, rd_diag, verbose, n_threads)
}

pace_random_design_block_cpp <- function(x_terms, cell_group, n_groups) {
    .Call(`_PACE_pace_random_design_block_cpp`, x_terms, cell_group, n_groups)
}

